#ifndef PRAGMA_TRITON_LIB_H
#define PRAGMA_TRITON_LIB_H

/*
** Aztec 'C', Maxon 'C' and StormC format pragma files
**
** Amiga specific files and diffs Copyright (C) 2025 amigazen project
** OpenTriton Copyright (C) 1993-1998 by OpenTriton Project
** Changes in 6.115 by amigazen project
** Refactoring for NDK3.2 by amigazen project
** This library is freely distributable under GPL terms
** This is the OpenTriton 2.0 release of the "triton.library" user
** interface creation and management tool kit.
**
** Generated by LibDescConverter from an sfd file
*/

#ifndef CLIB_TRITON_PROTOS_H
#include <clib/triton_protos.h>
#endif /* CLIB_TRITON_PROTOS_H */

/* "triton.library" */
/*--- functions in V80 or higher --- */
#pragma amicall(TritonBase, 0x1E, TR_OpenProject(a1,a0))
#pragma amicall(TritonBase, 0x24, TR_CloseProject(a0))
#pragma amicall(TritonBase, 0x2A, TR_FirstOccurance(d0,a0))
#pragma amicall(TritonBase, 0x30, TR_NumOccurances(d0,a0))
#pragma amicall(TritonBase, 0x36, TR_GetErrorString(d0))
#pragma amicall(TritonBase, 0x3C, TR_SetAttribute(a0,d0,d1,d2))
#pragma amicall(TritonBase, 0x42, TR_GetAttribute(a0,d0,d1))
#pragma amicall(TritonBase, 0x48, TR_LockProject(a0))
#pragma amicall(TritonBase, 0x4E, TR_UnlockProject(a0))
/*--- functions in V81 or higher --- */
#pragma amicall(TritonBase, 0x54, TR_AutoRequest(a1,a0,a2))
#pragma amicall(TritonBase, 0x5A, TR_EasyRequest(a1,a2,a3,a0))
#pragma amicall(TritonBase, 0x60, TR_CreateApp(a1))
#pragma amicall(TritonBase, 0x66, TR_DeleteApp(a1))
#pragma amicall(TritonBase, 0x6C, TR_GetMsg(a1))
#pragma amicall(TritonBase, 0x72, TR_ReplyMsg(a1))
#pragma amicall(TritonBase, 0x78, TR_Wait(a1,d0))
#pragma amicall(TritonBase, 0x7E, TR_CloseWindowSafely(a0))
#pragma amicall(TritonBase, 0x84, TR_GetLastError(a1))
#pragma amicall(TritonBase, 0x8A, TR_LockScreen(a0))
#pragma amicall(TritonBase, 0x90, TR_UnlockScreen(a0))
#pragma amicall(TritonBase, 0x96, TR_ObtainWindow(a0))
#pragma amicall(TritonBase, 0x9C, TR_ReleaseWindow(a0))
#pragma amicall(TritonBase, 0xA2, TR_SendMessage(a0,d0,d1,a1))
#pragma amicall(TritonBase, 0xA8, TR_AddClass(a1,d0,d1,a2,d2,a0))
/*--- functions in V180 or higher --- */
#pragma amicall(TritonBase, 0xAE, TR_DrawFrame(a0,a1,d1,d2,d3,d4,d0,d5))
#pragma amicall(TritonBase, 0xB4, TR_FrameBorderWidth(a0,d0))
#pragma amicall(TritonBase, 0xBA, TR_FrameBorderHeight(a0,d0))
#pragma amicall(TritonBase, 0xC0, TR_TextWidth(a0,a2,d0))
#pragma amicall(TritonBase, 0xC6, TR_TextHeight(a0,a2,d0))
#pragma amicall(TritonBase, 0xCC, TR_PrintText(a0,a1,a2,d1,d2,d3,d0))
#pragma amicall(TritonBase, 0xD2, TR_GetPen(a0,d0,d1))
#pragma amicall(TritonBase, 0xD8, TR_DoMethod(a0,d0,a1))
#pragma amicall(TritonBase, 0xDE, TR_DoMethodClass(a0,d0,a1,a2))
#pragma amicall(TritonBase, 0xE4, TR_AreaFill(a0,a1,d0,d1,d2,d3,d4,a2))
#pragma amicall(TritonBase, 0xEA, TR_CreateMsg(a1))

#endif /* PRAGMA_TRITON_LIB_H */
