#ifndef PRAGMAS_TRITON_PRAGMAS_H
#define PRAGMAS_TRITON_PRAGMAS_H

/*
** Lattice 'C', Aztec 'C', SAS/C and DICE format pragma files.
**
** Amiga specific files and diffs Copyright (C) 2025 amigazen project
** OpenTriton Copyright (C) 1993-1998 by OpenTriton Project
** Changes in 6.115 by amigazen project
** Refactoring for NDK3.2 by amigazen project
** This library is freely distributable under GPL terms
** This is the OpenTriton 2.0 release of the "triton.library" user
** interface creation and management tool kit.
**
** Generated by LibDescConverter from an sfd file
*/

#ifndef CLIB_TRITON_PROTOS_H
#include <clib/triton_protos.h>
#endif /* CLIB_TRITON_PROTOS_H */

/* "triton.library" */
/*--- functions in V80 or higher --- */
#pragma libcall TritonBase TR_OpenProject 1E 8902
#pragma libcall TritonBase TR_CloseProject 24 801
#pragma libcall TritonBase TR_FirstOccurance 2A 8002
#pragma libcall TritonBase TR_NumOccurances 30 8002
#pragma libcall TritonBase TR_GetErrorString 36 001
#pragma libcall TritonBase TR_SetAttribute 3C 210804
#pragma libcall TritonBase TR_GetAttribute 42 10803
#pragma libcall TritonBase TR_LockProject 48 801
#pragma libcall TritonBase TR_UnlockProject 4E 801
/*--- functions in V81 or higher --- */
#pragma libcall TritonBase TR_AutoRequest 54 A8903
#pragma libcall TritonBase TR_EasyRequest 5A 8BA904
#pragma libcall TritonBase TR_CreateApp 60 901
#pragma libcall TritonBase TR_DeleteApp 66 901
#pragma libcall TritonBase TR_GetMsg 6C 901
#pragma libcall TritonBase TR_ReplyMsg 72 901
#pragma libcall TritonBase TR_Wait 78 0902
#pragma libcall TritonBase TR_CloseWindowSafely 7E 801
#pragma libcall TritonBase TR_GetLastError 84 901
#pragma libcall TritonBase TR_LockScreen 8A 801
#pragma libcall TritonBase TR_UnlockScreen 90 801
#pragma libcall TritonBase TR_ObtainWindow 96 801
#pragma libcall TritonBase TR_ReleaseWindow 9C 801
#pragma libcall TritonBase TR_SendMessage A2 910804
#pragma libcall TritonBase TR_AddClass A8 82A10906
/*--- functions in V180 or higher --- */
#pragma libcall TritonBase TR_DrawFrame AE 5043219808
#pragma libcall TritonBase TR_FrameBorderWidth B4 0802
#pragma libcall TritonBase TR_FrameBorderHeight BA 0802
#pragma libcall TritonBase TR_TextWidth C0 0A803
#pragma libcall TritonBase TR_TextHeight C6 0A803
#pragma libcall TritonBase TR_PrintText CC 0321A9807
#pragma libcall TritonBase TR_GetPen D2 10803
#pragma libcall TritonBase TR_DoMethod D8 90803
#pragma libcall TritonBase TR_DoMethodClass DE A90804
#pragma libcall TritonBase TR_AreaFill E4 A432109808
#pragma libcall TritonBase TR_CreateMsg EA 901

#endif /* PRAGMAS_TRITON_PRAGMAS_H */
